### ISSUE TITLE
[Feature request] Custom primary key

### ISSUE THREAD

**Issue by KaKi87** [zeke/keyed-array#3]
Hello,

It would be nice to be able to choose by oneself which item key to use as primary.

Thanks

---

Also, I just read [your blog post](https://zeke.sikelianos.com/keyed-arrays-in-javascript/), a few hours after [posting one myself](https://sh.itjust.works/post/1117288) saying almost exactly[^1] the same things as you !!!

I'm glad I found it, because I was beginning to wonder if, possibly being alone with this idea, it could have been because it would just have been a bad one.

Although you wondered yourself :

> If you found this useful, let me know. If you think it's a bad idea, tell me why.

Did you get feedback on this ?

[^1]: My [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)-based solution, in addition to not having `length` & `JSON.stringify` issues, has mutability, although I didn't encounter a use case for that yet.

**Comment by zeke** [comment]
Hey. I don't use this any more, but I'd accept a PR to add support for that!

**Comment by KaKi87** [comment]
Actually, I created [my own lib](https://git.kaki87.net/KaKi87/hybrid-array) in the meantime, thanks anyway !
